/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

/**
 *
 * @author charmjunewonder
 */
public class LoginFrame extends javax.swing.JFrame {

	/**
	 * Creates new form LoginFrame
	 */
	public LoginFrame() {
		initComponents();
	}

	/**
	 * @return the genderButtonGroup
	 */
	public javax.swing.ButtonGroup getGenderButtonGroup() {
		return genderButtonGroup;
	}

	/**
	 * @return the femaleRadioButton
	 */
	public javax.swing.JRadioButton getFemaleRadioButton() {
		return femaleRadioButton;
	}

	/**
	 * @return the maleRadioButton
	 */
	public javax.swing.JRadioButton getMaleRadioButton() {
		return maleRadioButton;
	}

	/**
	 * @return the addressTextField
	 */
	public javax.swing.JTextField getAddressTextField() {
		return addressTextField;
	}

	/**
	 * @return the ageTextField
	 */
	public javax.swing.JTextField getAgeTextField() {
		return ageTextField;
	}

	/**
	 * @return the heightTextField
	 */
	public javax.swing.JTextField getHeightTextField() {
		return heightTextField;
	}

	/**
	 * @return the nameTextField
	 */
	public javax.swing.JTextField getNameTextField() {
		return nameTextField;
	}

	/**
	 * @return the patientNumberTextField
	 */
	public javax.swing.JTextField getPatientNumberTextField() {
		return patientNumberTextField;
	}

	/**
	 * @return the specificTextArea
	 */
	public javax.swing.JTextArea getSpecificTextArea() {
		return specificTextArea;
	}

	/**
	 * @return the weightTextField
	 */
	public javax.swing.JTextField getWeightTextField() {
		return weightTextField;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        patientNumerLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        specificLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        patientNumberTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        heightTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        specificTextArea = new javax.swing.JTextArea();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient Monitoring System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 36, -1, -1));

        nameLabel.setText("Name: ");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 100, -1, -1));

        addressLabel.setText("Address: ");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 149, -1, -1));

        patientNumerLabel.setText("PatientNumber: ");
        getContentPane().add(patientNumerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 192, -1, -1));

        ageLabel.setText("Age: ");
        getContentPane().add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 237, -1, -1));

        genderLabel.setText("Gender: ");
        getContentPane().add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 282, -1, -1));

        weightLabel.setText("Weight: ");
        getContentPane().add(weightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 327, -1, -1));

        heightLabel.setText("Height: ");
        getContentPane().add(heightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 367, -1, -1));

        specificLabel.setText("Specific Medician Condition: ");
        getContentPane().add(specificLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 408, -1, -1));

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 270, -1));

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 270, -1));
        getContentPane().add(patientNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 270, -1));
        getContentPane().add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 231, 271, -1));
        getContentPane().add(weightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 321, 271, -1));
        getContentPane().add(heightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 361, 271, -1));

        specificTextArea.setColumns(20);
        specificTextArea.setRows(5);
        jScrollPane1.setViewportView(specificTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 408, 271, -1));

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 278, -1, -1));

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 278, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_nameTextFieldActionPerformed

	private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_maleRadioButtonActionPerformed

	private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_femaleRadioButtonActionPerformed

	private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_addressTextFieldActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new LoginFrame().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField patientNumberTextField;
    private javax.swing.JLabel patientNumerLabel;
    private javax.swing.JLabel specificLabel;
    private javax.swing.JTextArea specificTextArea;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
